### ISSUE TITLE
First vs third-party servers as trust model technique

### ISSUE THREAD

**Issue by broggeri** [google/ads-privacy#45]
Referencing ads-privacy/trust-model/trust_techniques.md
> ### First vs third-party servers
> The entity that controls and runs the server will have considerable power over the servers.
> 
> If the entity has very strong incentives to uphold user privacy, for example, if it is a corporation whose public image is built on that, then the likelihood of the data being misused is lower.

The title of the paragraph is confusing. First vs third-party servers seem to have acquired a definite meaning in the context of a webpage displayed in a browser, and that meaning is irrelevant to the point being made here.

A couple suggestions of alternative titles:
- Server governance
- Operator incentives

**Comment by pjl-google** [comment]
Hey, thanks, that's a good idea.  I picked the first of your suggestions and I'll update the heading of that doc section in a moment.

Regards,
Phil
