### ISSUE TITLE
3PC deprecation 

### ISSUE THREAD

**Issue by AllianceDigitale** [google/ads-privacy#80]
Hi Google Chrome team,

During our recent meeting, you provided an explanation of the existing 3PC (Third-Party Cookies) depreciation timeline, which comprises the following phases:

January 2024: 

- A gradual increase in Chrome traffic without 3PC, reaching 1%.
- Q1-Q2 2024: No further ramp-up is planned during this period due to ongoing market testing.
- H2 2024: The depreciation process will recommence, aiming to achieve 100% 3PC depreciation by the year's end.

As previously discussed, we wish to highlight the concerns expressed by Alliance digitale regarding the proposed depreciation in Q4 2024. These concerns are grounded in the following considerations:

- Q4 represents a significant and busy period of the year, during which many adtech companies suspend their production deployments to mitigate potential disruptions.
- The ramp-up process for publishers is expected to require a considerable amount of time, and the current timeline appears to be rather stringent.
- The market is undergoing a period of flux characterized by fluctuating budgets that may shift between the open web and other platforms, along with evolving competitive dynamics.

While we acknowledge the necessity of resuming the depreciation process after the conclusion of market testing, we would like to propose an adjustment to the plan as follows:

1. Implement a complete freeze in Q4 2024.
2. Gradually ramp up outside of Q4, for instance, at a rate of 1% per day.

This approach would serve to safeguard the activity of our members during the crucial year-end period, without compromising the overall completion of the 3PC depreciation plan.

Sincerely,
Alliance Digitale

**Comment by rahulkooverjee-google** [comment]
Hi Alliance Digitale, 

We'd like to clarify that this repository (google/ads-privacy) is for the Google Ads team, not the Google Chrome team. Although we're part of the same company, we operate independently. So, for example, this repository is not monitored by the Chrome team. 

It seems like this feedback is meant to be addressed to the Chrome team, and so might be better suited to one of the Chrome repositories - perhaps https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues? 

Regards,
Rahul (PM for Google Ad Manager)

**Comment by AllianceDigitale** [comment]
Thanks: issue can be found here https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/158
